import { Listing } from '@/types';
import { addDays, subDays } from 'date-fns';

const today = new Date();

export const mockListings: Listing[] = [
  {
    id: '1',
    userId: 'u1',
    category: 'Train',
    status: 'Available',
    price: 800,
    numberOfTickets: 1,
    postedDate: subDays(today, 1).toISOString(),
    contactInfo: '+919876543210',
    trainNameOrNumber: 'Vande Bharat Express (22221)',
    fromStation: 'Mumbai (CSMT)',
    toStation: 'Pune (PUNE)',
    dateOfJourney: addDays(today, 2).toISOString(),
    departureTime: '16:00',
    arrivalTime: '19:10',
    travelClass: 'CC',
    pnrStatus: 'Confirmed',
  },
  {
    id: '2',
    userId: 'u2',
    category: 'Movies',
    status: 'Available',
    price: 300,
    numberOfTickets: 2,
    postedDate: subDays(today, 0).toISOString(),
    contactInfo: 'whatsapp: 9876543211',
    movieName: 'Oppenheimer',
    theatreName: 'PVR Phoenix Palladium',
    location: 'Mumbai',
    date: addDays(today, 1).toISOString(),
    showTiming: '20:30',
    seatNumbers: 'H12, H13',
  },
  {
    id: '3',
    userId: 'u3',
    category: 'Events',
    status: 'Sold',
    price: 1500,
    numberOfTickets: 4,
    postedDate: subDays(today, 3).toISOString(),
    contactInfo: 'student@college.edu',
    eventName: 'Sunburn Arena',
    venue: 'Bandra Kurla Complex',
    date: addDays(today, 10).toISOString(),
    time: '18:00',
  },
  {
    id: '4',
    userId: 'u4',
    category: 'Bus',
    status: 'Available',
    price: 500,
    numberOfTickets: 1,
    postedDate: subDays(today, 0).toISOString(),
    contactInfo: '9988776655',
    busOperator: 'Neeta Travels',
    fromLocation: 'Pune',
    toLocation: 'Goa',
    dateOfJourney: addDays(today, 1).toISOString(),
    departureTime: '22:00',
    arrivalTime: '07:30',
    seatType: 'Sleeper AC',
  }
];
